/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: a0a26190978e14eaec516175eb5b8703)
interface __BaseEnv_Env {
	DB: D1Database;
	ASSETS: Fetcher;
	ADMIN_USER_IDS: "";
	MODERATOR_USER_IDS: "";
	APPROVAL_THRESHOLD: "2";
	DISCORD_GUILD_ID: "";
	ADMIN_DISCORD_USER_IDS: "";
	GIPHY_API_KEY: "";
	CHAT_ROOMS: DurableObjectNamespace<import("./worker").ChatRoom>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
		durableNamespaces: "ChatRoom";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ADMIN_USER_IDS" | "MODERATOR_USER_IDS" | "APPROVAL_THRESHOLD" | "DISCORD_GUILD_ID" | "ADMIN_DISCORD_USER_IDS" | "GIPHY_API_KEY">> {}
}
